2015-08-19 20:03:41,339 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:03:41,339 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-19 20:09:42,626 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:09:42,626 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 14:17:23,087 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:17:23,087 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:17:23,140 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 466, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:17:23,140 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 466, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:22:12,781 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:22:12,781 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:22:12,784 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 453, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:22:12,784 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 453, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:23:52,500 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:23:52,500 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:38:24,147 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:38:24,147 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:41:23,681 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:41:23,681 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:42:50,158 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:42:50,158 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:42:51,153 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:42:51,153 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:42:51,154 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:42:51,154 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:43:12,820 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:43:12,820 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:46:52,757 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:46:52,757 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 18:00:11,935 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:00:11,935 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:09:55,098 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:09:55,098 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:10:11,297 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:10:11,297 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:10:11,297 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:10:11,297 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:11:22,473 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:11:22,473 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:11:27,714 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:11:27,714 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:11:27,714 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:11:27,714 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:23:51,941 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:23:51,941 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:23:53,086 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:23:53,086 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:23:53,086 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 18:23:53,086 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 18:37:55,338 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:37:55,338 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:37:59,615 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:37:59,615 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:37:59,615 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:37:59,615 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:48:50,997 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:48:50,997 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:48:54,869 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:48:54,869 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:48:54,870 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:48:54,870 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 18:56:51,925 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:56:51,925 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:56:58,277 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:56:58,277 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 18:56:58,277 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 18:56:58,277 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 18:57:04,334 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:57:04,334 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:57:49,655 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:57:49,655 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:59:11,627 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 18:59:11,627 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:01:48,645 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:01:48,645 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:05:58,069 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:05:58,069 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:05:58,069 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:05:58,069 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:08:11,602 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:08:11,602 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:08:12,653 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:08:12,653 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:08:12,653 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:08:12,653 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:08:18,673 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:08:18,673 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:08:22,202 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:08:22,202 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:08:22,202 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:08:22,202 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:09:23,827 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:09:23,827 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:09:25,036 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:09:25,036 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:09:25,036 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:09:25,036 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:12:40,046 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:12:40,046 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:12:42,299 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:12:42,299 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:12:42,299 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:12:42,299 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:12:51,572 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:12:51,572 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:12:51,573 - exploratory_analysis - DEBUG - dataset_name: test_data_cam5se
2015-08-20 19:12:51,573 - exploratory_analysis - DEBUG - dataset_name: test_data_cam5se
2015-08-20 19:29:16,034 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:29:16,034 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:29:16,037 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:29:16,037 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:30:45,783 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:30:45,783 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:30:45,784 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:30:45,784 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:31:01,865 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:31:01,865 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:31:01,868 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:31:01,868 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:31:06,681 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:31:06,681 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:31:06,681 - exploratory_analysis - DEBUG - dataset_name: test_data_cam5se
2015-08-20 19:31:06,681 - exploratory_analysis - DEBUG - dataset_name: test_data_cam5se
2015-08-20 19:36:48,608 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:36:48,608 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:36:48,611 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:36:48,611 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:36:52,847 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:36:52,847 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:36:52,847 - exploratory_analysis - DEBUG - dataset_name: test_data_cam5se
2015-08-20 19:36:52,847 - exploratory_analysis - DEBUG - dataset_name: test_data_cam5se
2015-08-20 19:49:04,998 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/views.py", line 172, in auth
    port=7512
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/myproxy_logon.py", line 131, in myproxy_logon_py
    raise GetException(errortext)
GetException: invalid password

2015-08-20 19:49:04,998 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/views.py", line 172, in auth
    port=7512
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/myproxy_logon.py", line 131, in myproxy_logon_py
    raise GetException(errortext)
GetException: invalid password

2015-08-20 19:49:15,544 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:49:15,544 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:49:15,545 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:49:15,545 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:49:18,667 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:49:18,667 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:49:18,687 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:49:18,687 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:58:13,870 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/views.py", line 172, in auth
    port=7512
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/myproxy_logon.py", line 131, in myproxy_logon_py
    raise GetException(errortext)
GetException: invalid username

2015-08-20 19:58:13,870 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/views.py", line 172, in auth
    port=7512
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/myproxy_logon.py", line 131, in myproxy_logon_py
    raise GetException(errortext)
GetException: invalid username

2015-08-20 19:58:25,948 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:58:25,948 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 19:58:25,951 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:58:25,951 - exploratory_analysis - DEBUG - 
In GET

2015-08-20 19:58:27,231 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:58:27,231 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 19:58:27,231 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-08-20 19:58:27,231 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-09-30 19:07:33,811 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/views.py", line 172, in auth
    port=7512
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/myproxy_logon.py", line 131, in myproxy_logon_py
    raise GetException(errortext)
GetException: invalid password

2015-09-30 19:07:33,811 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/views.py", line 172, in auth
    port=7512
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/exploratory_analysis/myproxy_logon.py", line 131, in myproxy_logon_py
    raise GetException(errortext)
GetException: invalid password

2015-09-30 19:08:08,172 - exploratory_analysis - DEBUG - 
In GET

2015-09-30 19:08:08,172 - exploratory_analysis - DEBUG - 
In GET

2015-09-30 19:08:08,174 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-09-30 19:08:08,174 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-09-30 19:08:09,977 - exploratory_analysis - DEBUG - 
In Variables GET

2015-09-30 19:08:09,977 - exploratory_analysis - DEBUG - 
In Variables GET

2015-09-30 19:08:09,977 - exploratory_analysis - DEBUG - dataset_name: cam5se
2015-09-30 19:08:09,977 - exploratory_analysis - DEBUG - dataset_name: cam5se
